version: '3.9'
services:
  personal_website:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    env_file: ./.env
    environment:
      - NODE_ENV=production
    expose:
      - '80'
    volumes:
      - ./:/home/node/app
    command: 'npm start'

  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt/live/cam-davis.com
    depends_on:
      - personal_website
    networks:
      - default 

networks:
  default:

volumes:
  web-root:
  personal_website:
