version: '3.9'
services:
  personal-website:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app/personal-website
    env_file: ./.env
    environment:
      - NODE_ENV=production
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./:/home/node/app
    command: 'npm start'
  blog:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app/blog
    env_file: ./.env
    environment:
      - NODE_ENV=production
    ports:
      - '81:81'
      - '444:444'
    volumes:
      - ./:/home/node/app
    command: 'npm start'
volumes:
  personal-website:
